### PR TITLE
Switching to yakh for stdin handling

### PR DESCRIPTION
**Pull request by petereon**
Third attempt to get a satisfactory `sys.stdin` handling with the features I am hoping for while trying my absolute best to cause as little mess as I thinkably can.

### CODE REVIEW

**Comment by petereon** [comment]
Should resolve #37 and #38

**Comment by petereon** [comment]
TODO: manual testing on Windows and Linux

**Comment by Cube707** [comment]
the use of the regex to check for escape-sequences is a fancy idea though

**Comment by petereon** [comment]
Yeah, it's fairly similar, I am not saying I haven't peeked into `readchar` several times, standing on the shoulders of giants so to say. But maan was it painful to get it to work with both `ESC` key and COPY-PASTING - with blocking stdin read it was either-or scenario. Nevertheless, I decided to go with non-blocking and handling nasty cases myself, having to abandon all the dignity in form of performance considerations and software design. But it is what it is :laughing:

**Pull request merged**
